#!/bin/bash

# Custom shell script
while true; do
    echo -n "#cisfun$ "
    read -r command  # Read user input into the 'command' variable
    eval "$command"  # Execute the command entered by the user using eval
while IFS= read -r command; do
    eval "$command"  # Execute the command entered by the user using eval
done
